### ISSUE TITLE
get the reference of a document

### ISSUE THREAD

**Issue by crisras27** [oslofjord/sanity-linq#20]
Hello Guys i do not know if this could be here or in StackOverflow. i am trying to do an API to insert documents in sanity CMS,
in one doument i have a reference to another one that saves the name and address but when i try to insert it with the create() method and send my person object i check in the admin studio and appear a texts that says "Must be a reference to a document"
how can i resolve the reference to a document to create it on sanity?

**Comment by rvanoord** [comment]
Hi,
You should probably save the document you are trying to reference first and
then add the saved document (with Id set) to the document that references
it using the SanityReference<> type. The readme in the repository shows how
this type can be used.

**Comment by crisras27** [comment]
yes i have been able to create that object but when i try to create a new document i search the employee with sanity.DocumentSet<Employee>().Where(h => h.Name == payload.EmployeeName).ToList();

after this i create my object to insert it in the sanity CMS but there i i am not able to convert to SanityReference cause i bring an Employee object

**Comment by rvanoord** [comment]
Hi,

When linking a referenced object, you cannot send in the object itself.
This would only work for nested objects which are part of the document,
rather than being referenced by the object.

In your case your entity model should probably look something like this:

public class MyEntity
{
   //your properties

   // reference to employee
   public SanityReference<Employee> Employee { get; set; } =  new
SanityReference<Employee>();

}

Before saving your entity you can do something like this;

var employee =  sanity.DocumentSet().Where(h => h.Name ==
payload.EmployeeName).FirstOrDefault();
var myEntity = new MyEntity();
myEntity.Employee.Value = employee;

**Comment by crisras27** [comment]
yes that shoulbe working thanks so much!!!!

have a nice day!!!!
